In [ ]:
## 맥 데스크톱에서 작업을 하던 중 폴더가 날아가 이전 작업이 사라졌음
## 넘파이 배열에 대한 기본지식은 study-note repository 에 기술함

pip install numpy

In [ ]:
import re, os
import usecsv
import numpy as np

In [ ]:
os.chdir(r'/Users/leekyungha/PycharmProjects/python-data-basic-programming/5-package-data-analysis/data')

In [ ]:
quest = np.array(usecsv.opencsv('quest.csv'))
quest

In [ ]:
# 여기 : 타입 안바뀜
# 해당 부분은 'usecsv' 모듈을 따로 만들어 사용
# 결과값으로 numpy.ndarray 로 나옴. 넘파이 배열로 만들어서 그런 것 같은데, 배열 내부 숫자 타입을 확인할 수 없음
usecsv.switch(quest)

type(quest)

In [ ]:
# 여기 : 타입 안바뀜
# 위에 모듈이 이상해 그런가 해서 직접 모듈에 있던 switch 함수를 불러왔으나, 같은 문제 발생
def switch(listName):
    for i in listName:
        for j in i:
            try:
                i[i.index(j)] = float(re.sub(',', '', j))
            except:
                pass
    return listName

switch(quest)

In [ ]:
# 이부분 오류
quest > 8

In [17]:

quest.astype('float64')

array([[1., 2., 1., 2., 2.],
       [1., 3., 2., 3., 2.],
       [1., 4., 3., 3., 3.],
       [2., 5., 4., 4., 4.],
       [2., 5., 6., 2., 5.],
       [3., 6., 4., 2., 5.],
       [3., 5., 4., 1., 6.],
       [3., 5., 5., 1., 3.]])

In [18]:
quest > 8

TypeError: '>' not supported between instances of 'numpy.ndarray' and 'int'

In [23]:
import re, os
import usecsv
import numpy as np

os.chdir(r'/Users/leekyungha/PycharmProjects/python-data-basic-programming/5-package-data-analysis/data')
quest = np.array(usecsv.opencsv('quest.csv'))

floatArray = quest.astype('float64')

print(floatArray)

[[1. 2. 1. 2. 2.]
 [1. 3. 2. 3. 2.]
 [1. 4. 3. 3. 3.]
 [2. 5. 4. 4. 4.]
 [2. 5. 6. 2. 5.]
 [3. 6. 4. 2. 5.]
 [3. 5. 4. 1. 6.]
 [3. 5. 5. 1. 3.]]


In [24]:

print(type(floatArray[0][0]))

<class 'numpy.float64'>


In [25]:
print(floatArray > 8)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [26]:
floatArray[floatArray > 5]

array([6., 6., 6.])

In [27]:
floatArray[floatArray > 5] = 5

In [30]:
floatArray

array([[1., 2., 1., 2., 2.],
       [1., 3., 2., 3., 2.],
       [1., 4., 3., 3., 3.],
       [2., 5., 4., 4., 4.],
       [2., 5., 5., 2., 5.],
       [3., 5., 4., 2., 5.],
       [3., 5., 4., 1., 5.],
       [3., 5., 5., 1., 3.]])

In [31]:
usecsv.writecsv('resultcsv.csv', list(floatArray))